
DROP TABLE IF EXISTS COMMENTAIRE;
CREATE TABLE COMMENTAIRE (
  ID_COMMENTAIRE int(11) NOT NULL AUTO_INCREMENT,
  COMPTEID int(11) DEFAULT NULL,
  ID_REPONSE int(11) DEFAULT NULL,
  DATE_AJOUTE timestamp NOT NULL DEFAULT current_timestamp(),
  COMM_CORE longtext DEFAULT NULL,
  DATE_EDIT datetime DEFAULT NULL,
  PRIMARY KEY (ID_COMMENTAIRE)
) ;

DROP TABLE IF EXISTS COMPTE;
CREATE TABLE COMPTE (
  COMPTEID int(11) NOT NULL AUTO_INCREMENT,
  EMAIL varchar(80) DEFAULT NULL,
  PASSWORD varchar(80) DEFAULT NULL,
  NOM varchar(40) DEFAULT NULL,
  PRENOM varchar(30) DEFAULT NULL,
  SEXE char(1) DEFAULT NULL CHECK (SEXE = 'F' or SEXE = 'H'),
  DATE_NAISSANCE date DEFAULT NULL,
  vcode int(11) DEFAULT 0,
  date_inscrit timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  TYPE char(1) DEFAULT NULL CHECK (TYPE = 'E' or TYPE = 'P'),
  PRIMARY KEY (COMPTEID),
  UNIQUE KEY EMAIL (EMAIL)
) ;

DROP TABLE IF EXISTS CONCERNE;
CREATE TABLE CONCERNE (
  POST_ID int(11) NOT NULL,
  ID_DOSSIER int(11) NOT NULL,
  PRIMARY KEY (POST_ID,ID_DOSSIER)
);

DROP TABLE IF EXISTS MODULE;
CREATE TABLE MODULE (
  ID_MODULE int(11) NOT NULL AUTO_INCREMENT,
  NOM_MODULE varchar(10) DEFAULT NULL,
  description text DEFAULT NULL,
  PRIMARY KEY (ID_MODULE)
);


DROP TABLE IF EXISTS DOCUMENT;
CREATE TABLE DOCUMENT (
  ID_DOCUMENT int(11) NOT NULL AUTO_INCREMENT,
  ID_MODULE int(11) DEFAULT NULL,
  NOM varchar(255) DEFAULT NULL,
  path longtext DEFAULT NULL,
  type char(1)  DEFAULT NULL CHECK (type = 'c' or type = 't' or type = 'h'),
  date_ajoute timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (ID_DOCUMENT),
  KEY ID_MODULE (ID_MODULE),
  CONSTRAINT DOCUMENT_ibfk_1 FOREIGN KEY (ID_MODULE) REFERENCES MODULE (ID_MODULE)
);

DROP TABLE IF EXISTS DOSSIER;
CREATE TABLE DOSSIER (
  ID_DOSSIER int(11) NOT NULL AUTO_INCREMENT,
  COMPTEID int(11) DEFAULT NULL,
  ID_MODULE int(11) DEFAULT NULL,
  nom_dossier varchar(40) DEFAULT NULL,
  PRIMARY KEY (ID_DOSSIER)
) ;
DROP TABLE IF EXISTS INSCRIT;

CREATE TABLE INSCRIT (
  ID_MODULE int(11) NOT NULL,
  COMPTEID int(11) NOT NULL,
  DATE_INSCRIT timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (ID_MODULE,COMPTEID),
  CONSTRAINT INSCRIT_ibfk_1 FOREIGN KEY (ID_MODULE) REFERENCES MODULE (ID_MODULE) ON DELETE CASCADE
);


DROP TABLE IF EXISTS POLL_ELEMENT;
CREATE TABLE POLL_ELEMENT (
  POLL_ID int(11) NOT NULL AUTO_INCREMENT,
  POST_ID int(11) DEFAULT NULL,
  ELEMENT varchar(100) DEFAULT NULL,
  VOTES int(11) DEFAULT 0,
  PRIMARY KEY (POLL_ID)
);

DROP TABLE IF EXISTS POLL_VOTE;
CREATE TABLE POLL_VOTE (
  POLL_ID int(11) NOT NULL,
  COMPTEID int(11) NOT NULL,
  PRIMARY KEY (POLL_ID,COMPTEID)
);

DROP TABLE IF EXISTS POST;
CREATE TABLE POST (
  POST_ID int(11) NOT NULL AUTO_INCREMENT,
  COMPTEID int(11) DEFAULT NULL,
  title varchar(200) NOT NULL,
  DATE_AJOUTE timestamp NOT NULL DEFAULT current_timestamp(),
  TYPE char(1) DEFAULT NULL,
  POST_CORE longtext DEFAULT NULL,
  DATE_EDIT datetime DEFAULT NULL,
  PRIMARY KEY (POST_ID)
);

DROP TABLE IF EXISTS REPONSE;
CREATE TABLE REPONSE (
  ID_REPONSE int(11) NOT NULL AUTO_INCREMENT,
  COMPTEID int(11) DEFAULT NULL,
  POST_ID int(11) DEFAULT NULL,
  DATE_AJOUTE timestamp NOT NULL DEFAULT current_timestamp(),
  REPONSE_CORE longtext DEFAULT NULL,
  VOTES int(11) DEFAULT 0,
  DATE_EDIT datetime DEFAULT NULL,
  PRIMARY KEY (ID_REPONSE)
);

DROP TABLE IF EXISTS UP_DOWN_VOTE;
CREATE TABLE UP_DOWN_VOTE (
  ID_REPONSE int(11) NOT NULL,
  COMPTEID int(11) NOT NULL,
  vote int(11) DEFAULT NULL CHECK (vote = 1 or vote = -1),
  PRIMARY KEY (ID_REPONSE,COMPTEID)
);

DROP TABLE IF EXISTS comment_notifications;
CREATE TABLE comment_notifications (
  notification_id int(11) NOT NULL AUTO_INCREMENT,
  COMPTEID int(11) DEFAULT NULL,
  ID_MODULE int(11) DEFAULT NULL,
  POST_ID int(11) DEFAULT NULL,
  ID_REPONSE int(11) DEFAULT NULL,
  ID_COMMENTAIRE int(11) DEFAULT NULL,
  date_ajoute timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (notification_id),
  KEY ID_COMMENTAIRE (ID_COMMENTAIRE),
  KEY ID_REPONSE (ID_REPONSE),
  KEY POST_ID (POST_ID),
  KEY ID_MODULE (ID_MODULE),
  KEY COMPTEID (COMPTEID),
  CONSTRAINT comment_notifications_ibfk_1 FOREIGN KEY (ID_COMMENTAIRE) REFERENCES COMMENTAIRE (ID_COMMENTAIRE) ON DELETE CASCADE,
  CONSTRAINT comment_notifications_ibfk_2 FOREIGN KEY (ID_REPONSE) REFERENCES REPONSE (ID_REPONSE) ON DELETE CASCADE,
  CONSTRAINT comment_notifications_ibfk_3 FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID) ON DELETE CASCADE,
  CONSTRAINT comment_notifications_ibfk_4 FOREIGN KEY (ID_MODULE) REFERENCES MODULE (ID_MODULE) ON DELETE CASCADE,
  CONSTRAINT comment_notifications_ibfk_5 FOREIGN KEY (COMPTEID) REFERENCES COMPTE (COMPTEID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS enseigner;
CREATE TABLE enseigner (
  COMPTEID int(11) NOT NULL,
  ID_MODULE int(11) NOT NULL,
  PRIMARY KEY (ID_MODULE,COMPTEID),
  KEY FK_enseigner1 (COMPTEID),
  CONSTRAINT FK_enseigner1 FOREIGN KEY (COMPTEID) REFERENCES COMPTE (COMPTEID) ON DELETE CASCADE,
  CONSTRAINT FK_enseigner2 FOREIGN KEY (ID_MODULE) REFERENCES MODULE (ID_MODULE) ON DELETE CASCADE
);

CREATE TABLE file (
  ID_file int(11) NOT NULL AUTO_INCREMENT,
  POST_ID int(11) DEFAULT NULL,
  ID_REPONSE int(11) DEFAULT NULL,
  file_path longtext DEFAULT NULL,
  file_name longtext DEFAULT NULL,
  PRIMARY KEY (ID_file)
);

DROP TABLE IF EXISTS posts_notifications;
CREATE TABLE posts_notifications (
  notification_id int(11) NOT NULL AUTO_INCREMENT,
  COMPTEID int(11) DEFAULT NULL,
  ID_MODULE int(11) DEFAULT NULL,
  POST_ID int(11) DEFAULT NULL,
  type char(1) DEFAULT NULL CHECK (type = 'q' or type = 'p' or type = 'n'),
  date_ajoute timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (notification_id),
  KEY POST_ID (POST_ID),
  KEY ID_MODULE (ID_MODULE),
  KEY COMPTEID (COMPTEID),
  CONSTRAINT posts_notifications_ibfk_1 FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID) ON DELETE CASCADE,
  CONSTRAINT posts_notifications_ibfk_2 FOREIGN KEY (ID_MODULE) REFERENCES MODULE (ID_MODULE) ON DELETE CASCADE,
  CONSTRAINT posts_notifications_ibfk_3 FOREIGN KEY (COMPTEID) REFERENCES COMPTE (COMPTEID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS reply_notifications;

CREATE TABLE reply_notifications (
  notification_id int(11) NOT NULL AUTO_INCREMENT,
  COMPTEID int(11) DEFAULT NULL,
  ID_MODULE int(11) DEFAULT NULL,
  POST_ID int(11) DEFAULT NULL,
  ID_REPONSE int(11) DEFAULT NULL,
  date_ajoute timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (notification_id),
  KEY ID_REPONSE (ID_REPONSE),
  KEY POST_ID (POST_ID),
  KEY ID_MODULE (ID_MODULE),
  KEY COMPTEID (COMPTEID),
  CONSTRAINT reply_notifications_ibfk_1 FOREIGN KEY (ID_REPONSE) REFERENCES REPONSE (ID_REPONSE) ON DELETE CASCADE,
  CONSTRAINT reply_notifications_ibfk_2 FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID) ON DELETE CASCADE,
  CONSTRAINT reply_notifications_ibfk_3 FOREIGN KEY (ID_MODULE) REFERENCES MODULE (ID_MODULE) ON DELETE CASCADE,
  CONSTRAINT reply_notifications_ibfk_4 FOREIGN KEY (COMPTEID) REFERENCES COMPTE (COMPTEID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS resources_notifications;
CREATE TABLE resources_notifications (
  notification_id int(11) NOT NULL AUTO_INCREMENT,
  COMPTEID int(11) DEFAULT NULL,
  ID_MODULE int(11) DEFAULT NULL,
  ID_DOCUMENT int(11) DEFAULT NULL,
  type char(1) DEFAULT NULL CHECK (type = 'c' or type = 't' or type = 'h'),
  date_ajoute timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (notification_id),
  KEY ID_DOCUMENT (ID_DOCUMENT),
  KEY ID_MODULE (ID_MODULE),
  KEY COMPTEID (COMPTEID),
  CONSTRAINT resources_notifications_ibfk_1 FOREIGN KEY (ID_DOCUMENT) REFERENCES DOCUMENT (ID_DOCUMENT) ON DELETE CASCADE,
  CONSTRAINT resources_notifications_ibfk_2 FOREIGN KEY (ID_MODULE) REFERENCES MODULE (ID_MODULE) ON DELETE CASCADE,
  CONSTRAINT resources_notifications_ibfk_3 FOREIGN KEY (COMPTEID) REFERENCES COMPTE (COMPTEID) ON DELETE CASCADE
);

